# -*- coding: utf-8 -*-
"""assignment2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g3Ty1hoeEfWtPxaOEdJ-bhvE8O-FcS5i
"""

from socket import *
class Assignment2():
   #constructor
   def __init__(self, year): #birthyear
    self.year = year

   def tellAge(self,currentYear):
     self.currentYear=currentYear
     print("Your age is ",self.currentYear-self.year)
     self.age=self.currentYear-self.year 
  
   def listAnniversaries(self):
     list = []
     i=10
     while (True):
      if i<=self.age:
         list.append(i)
      else:
        break   
      i=i+10
     return list
     
   def modifyYear(self,n):
       self.res =str(self.currentYear)
       num1=str(self.res[:2])
      #num2=str(self.res[-2:])
       num3=""
       for i in range(0,len(self.res),2):
         num3+= str(6)#str(self.res[i])
       result=""
       for i in range(n):
         result +=str(num1)
       #for i in range(n):
       #result +=str(num2)
       for i in range(1):
         result +=str(num3)
       return result
    
   @staticmethod
   def checkGoodString(string):
     if len(string)<9:
       return False

     if string[0].islower() == False:
       return False

     _num_count = 0
     for i in string:
         if i.isdigit():
            _num_count += 1 

         if _num_count > 1:
            return False

     return True

   def connectTcp(host, port):
     try:
         s = socket(AF_INET, SOCK_STREAM)
         host_address = gethostbyname(host)
         s.connect((host_address, port))
         s.close
         return True
     except: 
       return False


   


a=Assignment2(2000)

a.tellAge(2022)

ret=a.listAnniversaries()

print(ret)

#2022 * 3 = [6],0[6]6
print(a.modifyYear(3))

ret=Assignment2.checkGoodString("f1obar0more")
print(ret)
ret=Assignment2.checkGoodString("foobar0more")
print(ret)

retval = Assignment2.connectTcp("www.google.com",80)
if retval:
  print("Conection established correctly")
else:
    print("Some error")